# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from gerenciador import Tarefa
from gerenciador import GerenciadorDeTarefas


class Ui_GerenciadorDeTarefas_tela(object):
    def setupUi(self, GerenciadorDeTarefas_tela):
        GerenciadorDeTarefas_tela.setObjectName("GerenciadorDeTarefas_tela")
        GerenciadorDeTarefas_tela.resize(540, 433)
        self.centralwidget = QtWidgets.QWidget(parent=GerenciadorDeTarefas_tela)
        self.centralwidget.setObjectName("centralwidget")
        self.corpo = QtWidgets.QLabel(parent=self.centralwidget)
        self.corpo.setEnabled(True)
        self.corpo.setGeometry(QtCore.QRect(0, 40, 541, 391))
        self.corpo.setMinimumSize(QtCore.QSize(541, 391))
        self.corpo.setMaximumSize(QtCore.QSize(541, 391))
        self.corpo.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(194, 194, 194);\n"
"")
        self.corpo.setText("")
        self.corpo.setObjectName("corpo")
        self.Titulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(10, 20, 441, 41))
        self.Titulo.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"font: 63 26pt \"Sitka Small Semibold\";")
        self.Titulo.setObjectName("Titulo")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 160, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_button.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.list_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.list_button.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.list_button.setObjectName("list_button")
        self.verticalLayout.addWidget(self.list_button)
        self.listprio_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.listprio_button.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.listprio_button.setObjectName("listprio_button")
        self.verticalLayout.addWidget(self.listprio_button)
        self.remove_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.remove_button.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout.addWidget(self.remove_button)
        self.finish_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.finish_button.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.finish_button.setObjectName("finish_button")
        self.verticalLayout.addWidget(self.finish_button)
        self.cabecalho = QtWidgets.QLabel(parent=self.centralwidget)
        self.cabecalho.setGeometry(QtCore.QRect(0, 0, 541, 91))
        self.cabecalho.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.cabecalho.setText("")
        self.cabecalho.setObjectName("cabecalho")
        self.log = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.log.setGeometry(QtCore.QRect(330, 110, 181, 271))
        self.log.setObjectName("log")
        self.nometarefa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nometarefa.setGeometry(QtCore.QRect(190, 150, 113, 20))
        self.nometarefa.setObjectName("nometarefa")
        self.descricao = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.descricao.setGeometry(QtCore.QRect(190, 200, 113, 20))
        self.descricao.setObjectName("descricao")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 240, 69, 22))
        self.comboBox.setStyleSheet("background-color: rgb(155, 155, 155);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 220, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 120, 201, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 170, 171, 20))
        self.label_3.setObjectName("label_3")
        self.corpo.raise_()
        self.verticalLayoutWidget.raise_()
        self.cabecalho.raise_()
        self.Titulo.raise_()
        self.log.raise_()
        self.nometarefa.raise_()
        self.descricao.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        GerenciadorDeTarefas_tela.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=GerenciadorDeTarefas_tela)
        self.statusbar.setObjectName("statusbar")
        GerenciadorDeTarefas_tela.setStatusBar(self.statusbar)

        self.retranslateUi(GerenciadorDeTarefas_tela)
        QtCore.QMetaObject.connectSlotsByName(GerenciadorDeTarefas_tela)

        self.add_button.clicked.connect(lambda: self.adicionar(self.nometarefa.text(), self.descricao.text(), self.comboBox.currentText(),gerenciador))
        self.list_button.clicked.connect(lambda:self.list(gerenciador))
        self.listprio_button.clicked.connect(lambda:self.list_prio(gerenciador))
        self.remove_button.clicked.connect(lambda:self.remove(gerenciador,self.nometarefa.text()))
        self.finish_button.clicked.connect(lambda: self.finished(gerenciador, self.nometarefa.text()))
    def retranslateUi(self, GerenciadorDeTarefas_tela):
        _translate = QtCore.QCoreApplication.translate
        GerenciadorDeTarefas_tela.setWindowTitle(_translate("GerenciadorDeTarefas_tela", "MainWindow"))
        self.Titulo.setText(_translate("GerenciadorDeTarefas_tela", "Gerenciador de tarefas"))
        self.add_button.setText(_translate("GerenciadorDeTarefas_tela", "Adicionar tarefa"))
        self.list_button.setText(_translate("GerenciadorDeTarefas_tela", "listar tarefas"))
        self.listprio_button.setText(_translate("GerenciadorDeTarefas_tela", "listar tarefas prioritárias"))
        self.remove_button.setText(_translate("GerenciadorDeTarefas_tela", "remover tarefa"))
        self.finish_button.setText(_translate("GerenciadorDeTarefas_tela", "marcar como concluida"))
        self.comboBox.setItemText(0, _translate("GerenciadorDeTarefas_tela", "Sim"))
        self.comboBox.setItemText(1, _translate("GerenciadorDeTarefas_tela", "Não"))
        self.label.setText(_translate("GerenciadorDeTarefas_tela", "esta tarefa é uma prioridade?"))
        self.label_2.setText(_translate("GerenciadorDeTarefas_tela", "insira o nome da tarefa"))
        self.label_3.setText(_translate("GerenciadorDeTarefas_tela", "escreva a descrição da tarefa"))
    def aux(self, prio):
        if prio == "Sim":
            return True
        else:
            return False

    def adicionar(self, nome, descr, prio,gerenciador):
        self.log.setPlainText('')
        tarefa = Tarefa(nome, descr, self.aux(prio))
        self.log.appendPlainText("Tarefa adicionada:" + str(tarefa))
        gerenciador.adicionar_tarefa(tarefa)
        print(tarefa)
        return tarefa

    def list(self,gerenciador):
        self.log.setPlainText('')
        self.log.appendPlainText("todas as tarefas:\n")
        tarefas = gerenciador.tree.inorder()
        for tarefa in tarefas:
            self.log.appendPlainText(str(tarefa))
        return gerenciador.listar_tarefas()

    #self.log.appendPlainText
    def list_prio(self,gerenciador):
        self.log.setPlainText('')
        self.log.appendPlainText("Tarefas prioritarias:\n")
        tarefas = gerenciador.tarefas_prioritarias.traverse()
        for tarefa in tarefas:
            self.log.appendPlainText(str(tarefa))

        return gerenciador.navegar_tarefas_prioritarias()

    def remove(self,gerenciador,nome):
        self.log.setPlainText('')
        self.log.appendPlainText("Tarefa: " + str(nome) + " removida")
        gerenciador.remover_tarefa(nome)
    def finished(self,gerenciador,nome):
        self.log.setPlainText('')
        self.log.appendPlainText("Tarefa: " + str(nome) + " marcada com concluida!")
        gerenciador.marcar_concluida(nome)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GerenciadorDeTarefas_tela = QtWidgets.QMainWindow()
    ui = Ui_GerenciadorDeTarefas_tela()
    ui.setupUi(GerenciadorDeTarefas_tela)
    GerenciadorDeTarefas_tela.show()
    gerenciador = GerenciadorDeTarefas()
    sys.exit(app.exec())
